# Generated by Django 3.2.19 on 2023-05-20 18:04

import datetime
from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[restaurant.models.Booking.Date_validation]),
        ),
    ]
